---
title: "HGPE"
output:
  html_document:
    toc: yes
    toc_depth: '6'
  word_document:
    toc: yes
    toc_depth: '6'
  pdf_document:
    toc: yes
    toc_depth: '6'
---

```{r setup, include=FALSE, message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
library(ggpubr) #annotate_figure
library(readxl)
library(ggrepel)#geom_label_repel
library(sjPlot)
library(patchwork)
## abrir o bancos em csv e Rda
tempo_tv <- read_excel("tempo_tv.xlsx")

banco_hgpe <- read_csv("banco-HGPE.csv", 
    col_types = cols(Data = col_date(format = "%d/%m/%Y")))

disputas <- read_csv("disputas.csv")
load("dt_campos.Rda")

```

```{r echo=FALSE}

dt_campos <- dt_campos %>% 
  mutate(votos_validos = sum(Número.de.votos),
         perc_votos = Número.de.votos/votos_validos*100)




```


## Tempo de horário eleitoral disponível para cada candidato e voto

```{r echo=FALSE, fig.height=10, fig.width=15, warning=FALSE, message=FALSE}

##a confecccao do banco dt_campos esta aqui, mas nao tem como ser reproduzida pois o banco de despesas candidatos 
#esta no repositório dados_eleicoes. 
# gastos_campos <- despesas_contratadas_cand_20 %>% 
#   filter(NM_UE == "CAMPOS DOS GOYTACAZES",
#          CD_CARGO == 11) %>% 
#   group_by(NM_CANDIDATO, NR_CANDIDATO) %>% 
#   summarise(soma = sum(VR_DESPESA_CONTRATADA))
# tempo_tv <- read.csv("tempo_tv.xlsx - Planilha1.csv", dec = ",")
# 
# gastos_campos <- as.data.frame(gastos_campos)
# gastos_campos <- gastos_campos[-6,]
# 
# dt_campos <- left_join(tempo_tv, gastos_campos, by= "NR_CANDIDATO")

dt_campos %>% 
ggplot(aes(x = Tempo.em.segundos, y = perc_votos, colour = Candidato, size =soma)) +
  geom_point()+
  geom_smooth(formula= y ~ x, colour= "#6794a7", fill = "#6794a7", method='lm', span = 0.4, alpha = 0.1)+
  geom_label_repel(aes(label = Candidato),
                  size = 6,
                  box.padding   = 0.35, 
                  point.padding = 0.5)+
  #geom_text(aes(label= Candidato, size = NULL, color = Candidato), hjust = 0.5, vjust=1.9)+
  theme_fivethirtyeight()+
  ylab("Percentual de votos") + xlab("Tempo em Segundos")+
  labs(title = "Tempo de Propaganda Eleitoral Gratuita e voto", col = "#6794a7", fill = NULL)+
  theme(axis.title.x = element_text(size = 18), 
        axis.title.y = element_text(size = 18),
        axis.text.y = element_text(size = 18),
        axis.text.x = element_text(size = 18),
        title = element_text(size = 18),
        panel.background = element_rect(fill = "white", colour = "white", color = "white"),
        plot.background = element_rect(fill = "white", colour = "white", color = "white"),
        legend.background=element_rect(fill="white"),
        legend.key = element_rect(fill = "white", color = "white"),
        strip.background=element_rect(fill="white", colour="white"),
        panel.grid.major.x = element_line(colour= "#eceff2"),
        panel.grid.major.y = element_line(colour= "#eceff2"),
        legend.position = "none")


#mod <- lm(data = dt_campos, perc_votos ~ Tempo.em.segundos)

#tab_model(mod,  show.std = T)


```


## gráfico de linhas condidatos a prefeitura de campos 

```{r warning=FALSE, message=FALSE, echo=FALSE}

disputas %>% 
  ggplot(aes(x=Eleicao_Municipal, y=Total_cand_pref), col = "#6794a7")+
  geom_line(stat = "identity", color = "#6794a7", size = 1.8, alpha = 0.8)+
  geom_point(size= 3, color = "#6794a7", alpha = 0.8)+
  scale_x_continuous(breaks = c(2004,2008,2012,2016,2020))+
  theme_fivethirtyeight()+
  ylab("Total de canddidatos") + 
  labs(title = "Total de candidatos a prefeito em Campos dos Goytacazes", x = NULL)+
  theme(axis.title.x = element_text(size = 12), 
        axis.title.y = element_text(size = 12),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_text(size = 12),
        plot.subtitle = element_text(size = 10),
        legend.text = element_text(size = 14),
        title = element_text(size = 10),
        panel.background = element_rect(fill = "white", colour = "white", color = "white"),
        plot.background = element_rect(fill = "white", colour = "white", color = "white"),
        legend.background=element_rect(fill="white"),
        legend.key = element_rect(fill = "white", color = "white"),
        strip.background=element_rect(fill="white", colour="white"), 
        panel.grid.major.x = element_line(colour= "#eceff2"),
        panel.grid.major.y = element_line(colour= "#eceff2"))
  
  

```



```{r include= FALSE, warning=FALSE, message=FALSE}

### Transformou o banco em long 

hgpe_assuntos <- banco_hgpe %>% 
 pivot_longer(cols = starts_with("A_"), names_to = "Assuntos", values_to = "N") 


##transformou em long por assunto e recategorizou as variáveis Assuntos

assuntos_long <- hgpe_assuntos %>% 
  group_by(Assuntos) %>% 
  summarise(n_assuntos = sum(N, na.rm = TRUE))  %>% 
  mutate(perc_assuntos = n_assuntos/sum(n_assuntos)*100, 
         soma = sum(n_assuntos),
        Assuntos=case_when(Assuntos == "A_1"~"Governo atual (-)",
                           Assuntos == "A_2"~"Governo atual (+)", 
                           Assuntos == "A_3"~"Governos anterios (+)",
                           Assuntos == "A_4"~"Governos anterios (-)",
                           Assuntos == "A_5"~"Assistência Social",
                           Assuntos == "A_6"~"Capacidade Profissional", 
                           Assuntos == "A_7"~"Venda do futuro",
                           Assuntos == "A_8"~"Conexão com atores políticos", 
                           Assuntos == "A_9"~"Conexão com Partido Político", 
                           Assuntos == "A_10"~"Corrupção", 
                           Assuntos == "A_11"~"Educação",
                           Assuntos == "A_12"~"Emprego/Renda",
                           Assuntos == "A_13"~"Família",
                           Assuntos == "A_14"~"Lazer",
                           Assuntos == "A_15"~"Moradia",
                           Assuntos == "A_16"~"Pagamento de dívidas",
                           Assuntos == "A_17"~"Arrecadação Municipal(-)",
                           Assuntos == "A_18"~"Saúde",
                           Assuntos == "A_19"~"Transporte",
                           Assuntos == "A_20"~"Religião",
                           Assuntos == "A_21"~"P.P. p/ Mulher",
                           Assuntos == "A_22"~"Cultura",
                           Assuntos == "A_23"~"Covid-19",
                           Assuntos == "A_24"~"Saneamento básico",
                           Assuntos == "A_25"~"Infraestrutura",
                           Assuntos == "A_26"~"Pesquisa de Intenção de votos",
                           Assuntos == "A_27"~"Conexão com o legislativo",
                           Assuntos == "A_28"~"Incapacidade profissional",
                           Assuntos == "A_29"~"Servidores Públicos muni.",
                           Assuntos == "A_30"~"Agricultura",
                           Assuntos == "A_31"~"Segurança Pública",
                           Assuntos == "A_32"~"Turismo")) 


## criou o banco - Percentual de assuntos por candidatos

banco_cand_perc <- hgpe_assuntos %>%
    group_by(Candidatos, Assuntos) %>% 
    summarise(n_assuntos = sum(N, na.rm = TRUE)) %>% 
    group_by(Candidatos) %>% 
    mutate(perc = n_assuntos/sum(n_assuntos)*100,
           perc_100 = sum(perc),
           Assuntos=case_when(Assuntos == "A_1"~"Governo atual (-)",
                           Assuntos == "A_2"~"Governo atual (+)", 
                           Assuntos == "A_3"~"Governos anterios (+)",
                           Assuntos == "A_4"~"Governos anterios (-)",
                           Assuntos == "A_5"~"Assistência Social",
                           Assuntos == "A_6"~"Capacidade Profissional", 
                           Assuntos == "A_7"~"Venda do futuro",
                           Assuntos == "A_8"~"Conexão com atores políticos", 
                           Assuntos == "A_9"~"Conexão com Partido Político", 
                           Assuntos == "A_10"~"Corrupção", 
                           Assuntos == "A_11"~"Educação",
                           Assuntos == "A_12"~"Emprego/Renda",
                           Assuntos == "A_13"~"Família",
                           Assuntos == "A_14"~"Lazer",
                           Assuntos == "A_15"~"Moradia",
                           Assuntos == "A_16"~"Pagamento de dívidas",
                           Assuntos == "A_17"~"Arrecadação Municipal(-)",
                           Assuntos == "A_18"~"Saúde",
                           Assuntos == "A_19"~"Transporte",
                           Assuntos == "A_20"~"Religião",
                           Assuntos == "A_21"~"P.P. p/ Mulher",
                           Assuntos == "A_22"~"Cultura",
                           Assuntos == "A_23"~"Covid-19",
                           Assuntos == "A_24"~"Saneamento básico",
                           Assuntos == "A_25"~"Infraestrutura",
                           Assuntos == "A_26"~"Pesquisa de Intenção de votos",
                           Assuntos == "A_27"~"Conexão com o legislativo",
                           Assuntos == "A_28"~"Incapacidade profissional",
                           Assuntos == "A_29"~"Servidores Públicos muni.",
                           Assuntos == "A_30"~"Agricultura",
                           Assuntos == "A_31"~"Segurança Pública",
                           Assuntos == "A_32"~"Turismo"))



 
 
```

## Principais assuntos das eleicoes municípais de 2020



```{r echo=FALSE, fig.height=20, fig.width=15}

assuntos_long %>% 
   ggplot(aes(x = fct_reorder(Assuntos, n_assuntos), y=n_assuntos))+
   geom_bar(stat = "identity", color = "#6794a7", fill = "#6794a7", 
            alpha = 0.8)+
  coord_polar()+
   theme_fivethirtyeight()+
   labs(title = "Frequência de Assuntos Abordados HGPE - 2020", x= "")+
   theme(axis.title.x = element_text(size = 12), 
        axis.text.y = element_text(size = 16),
        axis.text.x = element_text(size = 16),
        title = element_text(size = 18),
        panel.background = element_rect(fill = "white", colour = "white", color = "white"),
        plot.background = element_rect(fill = "white", colour = "white", color = "white"),
        legend.background=element_rect(fill="white"),
        legend.key = element_rect(fill = "white", color = "white"),
        strip.background=element_rect(fill="white", colour="white"),
        panel.grid.major.x = element_line(colour= "#eceff2"),
        panel.grid.major.y = element_line(colour= "#eceff2"))
   
```


```{r echo=FALSE, fig.height=15, fig.width=12}

## Wladimir Garotinho

fig1 <- banco_cand_perc %>% 
  filter(Candidatos == "Wladimir Garotinho") %>% 
  ggplot(aes(y = fct_reorder(Assuntos, perc), x=perc))+
   geom_bar(stat = "identity", color = "#6794a7", fill = "#6794a7", 
            alpha = 0.9)+
   labs(title = "Wladimir Garotinho")+
   theme_fivethirtyeight()+ xlab("Percentual") + 
   theme(axis.title.x = element_text(size = 24), 
        axis.text.y = element_text(size = 24),
        axis.text.x = element_text(size = 24),
        title = element_text(size = 18),
        panel.background = element_rect(fill = "white", colour = "white", color = "white"),
        plot.background = element_rect(fill = "white", colour = "white", color = "white"),
        legend.background=element_rect(fill="white"),
        strip.background=element_rect(fill="white", colour="white"),
        panel.grid.major.x = element_line(colour= "#eceff2"),
        panel.grid.major.y = element_line(colour= "#eceff2"))

```

```{r echo=FALSE, fig.height=15, fig.width=12}

## Caio Viana

fig2 <- banco_cand_perc %>% 
  filter(Candidatos == "Caio Viana") %>% 
  ggplot(aes(y = fct_reorder(Assuntos, perc), x=perc))+
   geom_bar(stat = "identity", color = "#6794a7", fill = "#6794a7", 
            alpha = 0.9)+
   labs(title = "Caio Viana")+
   theme_fivethirtyeight()+ xlab("Percentual") + 
   theme(axis.title.x = element_text(size = 24), 
        axis.text.y = element_text(size = 24),
        axis.text.x = element_text(size = 24),
        title = element_text(size = 18),
        plot.subtitle = element_text(size = 24),
        legend.text = element_text(size = 24),
        panel.background = element_rect(fill = "white", colour = "white", color = "white"),
        plot.background = element_rect(fill = "white", colour = "white", color = "white"),
        legend.background=element_rect(fill="white"),
        strip.background=element_rect(fill="white", colour="white"),
        panel.grid.major.x = element_line(colour= "#eceff2"),
        panel.grid.major.y = element_line(colour= "#eceff2"))


```

```{r echo=FALSE, fig.height=15, fig.width=12}

## Dr. Bruno

fig3 <- banco_cand_perc %>% 
  filter(Candidatos == "Dr. Bruno") %>% 
  ggplot(aes(y = fct_reorder(Assuntos, perc), x=perc))+
   geom_bar(stat = "identity", color = "#6794a7", fill = "#6794a7", 
            alpha = 0.9)+
   labs(title = "Dr. Bruno")+
   theme_fivethirtyeight()+ xlab("Percentual") + 
   theme(axis.title.x = element_text(size = 24), 
        axis.text.y = element_text(size = 24),
        axis.text.x = element_text(size = 24),
        title = element_text(size = 18),
        plot.subtitle = element_text(size = 24),
        legend.text = element_text(size = 24),
        panel.background = element_rect(fill = "white", colour = "white", color = "white"),
        plot.background = element_rect(fill = "white", colour = "white", color = "white"),
        legend.background=element_rect(fill="white"),
        strip.background=element_rect(fill="white", colour="white"),
        panel.grid.major.x = element_line(colour= "#eceff2"),
        panel.grid.major.y = element_line(colour= "#eceff2"))

```

```{r echo=FALSE, fig.height=15, fig.width=12}

## Rafael Diniz

fig4 <- banco_cand_perc %>% 
  filter(Candidatos == "Rafael Diniz") %>% 
  ggplot(aes(y = fct_reorder(Assuntos, perc), x=perc))+
   geom_bar(stat = "identity", color = "#6794a7", fill = "#6794a7", 
            alpha = 0.9)+
   labs(title = "Rafael Diniz")+
   theme_fivethirtyeight()+ xlab("Percentual") + 
   theme(axis.title.x = element_text(size = 24), 
        axis.text.y = element_text(size = 24),
        axis.text.x = element_text(size = 24),
        title = element_text(size = 18),
        plot.subtitle = element_text(size = 24),
        legend.text = element_text(size = 24),
        panel.background = element_rect(fill = "white", colour = "white", color = "white"),
        plot.background = element_rect(fill = "white", colour = "white", color = "white"),
        legend.background=element_rect(fill="white"),
        strip.background=element_rect(fill="white", colour="white"), 
        panel.grid.major.x = element_line(colour= "#eceff2"),
        panel.grid.major.y = element_line(colour= "#eceff2"))
```

```{r echo=FALSE, fig.height=15, fig.width=12}

## Professora Natália

fig5 <- banco_cand_perc %>% 
  filter(Candidatos == "Professora Natália") %>% 
  ggplot(aes(y = fct_reorder(Assuntos, perc), x=perc))+
   geom_bar(stat = "identity", color = "#6794a7", fill = "#6794a7", 
            alpha = 0.9)+
   labs(title = "Professora Natália")+
   theme_fivethirtyeight()+ xlab("Percentual") + 
   theme(axis.title.x = element_text(size = 24), 
        axis.text.y = element_text(size = 24),
        axis.text.x = element_text(size = 24),
        title = element_text(size = 18),
        plot.subtitle = element_text(size = 24),
        legend.text = element_text(size = 24),
        panel.background = element_rect(fill = "white", colour = "white", color = "white"),
        plot.background = element_rect(fill = "white", colour = "white", color = "white"),
        legend.background=element_rect(fill="white"),
        strip.background=element_rect(fill="white", colour="white"),
        panel.grid.major.x = element_line(colour= "#eceff2"),
        panel.grid.major.y = element_line(colour= "#eceff2"))

```


```{r echo=FALSE, fig.height=45, fig.width=25}

# figure2 <- ggarrange(fig1, fig2, fig3, fig4, fig5, ncol=2, nrow=5, common.legend = TRUE, legend="bottom")
# 
# annotate_figure(figure2,
#                top = text_grob("Principais Assuntos Abordados por Candidato", color = "black", face = "bold", size = 20),
#                bottom = text_grob("Elaborado pelos autores", color = "black",
#                                   hjust = 1, x = 1, size = 10))



(fig1+fig2)/(fig3+fig4)/(fig5)


```


